# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
#45 
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match( app_identifier: "com.ranareda1.RamsesSuperApp",type: "appstore" )
    #increment_build_number(xcodeproj: "Ramses.xcodeproj")
    build_app(workspace: "Ramses.xcworkspace", scheme: "Ramses", teamId: "3CHW67J632")
    upload_to_testflight
    pilot(api_key_path: "fastlane/store.json", skip_waiting_for_build_processing: true)
  end
end
