name: deplopy an internal release for android

env:
  # The name of the main module repository
  main_project_module: Ramses.Superapp

  # The name of the Play Store
  playstore_name: Ramses

  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  # KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        #ubuntu
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.0"

        # Install dependencies
      - name: Install npm dependencies
        run: npm install

      - name: Install dependencies
        run: |
          npm install react-native
          npm install @react-native-community/cli-platform-android --force

      - name: Validate Android Configuration
        run: npx react-native config

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: "default"
          arch: "x86_64"

      - name: Set environment variables
        run: echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV

      - name: Increase Gradle memory allocation
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties

      - name: Change Gradle Wrapper Permissions
        run: |
          cd android
          chmod +x ./gradlew

      - name: Decode keystore
        run: |
          mkdir -p android/app/build/outputs/bundle/release
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/build/outputs/bundle/release/my-release-key.jks
        env:
          KEYSTORE_FILE_PATH: ${{ github.workspace }}/my-release-key.jks

      # - name: Clean project
      #   run: |
      #     cd android
      #     ./gradlew clean
      - name: Build Android App
        run: |
          cd android
          ./gradlew assembleRelease
      - name: Build Android AAB
        run: |
          cd android
          ./gradlew bundleRelease

      #   - name: Upload APK Release - ${{ env.repository_name }}
      #     uses: actions/upload-artifact@v3
      #     with:
      #       name: ${{ env.date_today }} - Ramses.Superapp - APK(s) release generated
      #       path: android/app/build/outputs/apk/release/app-release.apk

      #   - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
      #     uses: actions/upload-artifact@v3
      #     with:
      #       name: ${{ env.date_today }} - Ramses.Superapp - App bundle(s) AAB release generated
      #       path: android/app/build/outputs/bundle/release/

      - name: Sign APK
        run: |
          jarsigner -verbose -keystore "${{ github.workspace }}/android/app/build/outputs/bundle/release/my-release-key.jks" -storepass "${{ secrets.KEYSTORE_PASSWORD }}" "${{ github.workspace }}/android/app/build/outputs/apk/release/app-release-unsigned.apk" "${{ secrets.KEY_ALIAS }}"

      - name: Sign AAB
        run: |
          jarsigner -verbose -keystore android/app/build/outputs/bundle/release/my-release-key.jks -storepass "$KEYSTORE_PASSWORD" -keypass "$KEYSTORE_PASSWORD" android/app/build/outputs/bundle/release/app-release.aab "$KEY_ALIAS"
        continue-on-error: true

      #   - name: Upload AAB-signed
      #     uses: actions/upload-artifact@v3
      #     with:
      #       name: Ramses.Superapp - App bundle(s) AAB release signed
      #       path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: "com.ranareda1.RamsesSuperApp"
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
 